assets:
    css:
        - meta.css
    js: []
schema:
    $schema: 'http://json-schema.org/draft-04/schema#'
    type: object
    properties:
        typeLink:
            type: string
            minLength: 1
        type:
            type: string
            minLength: 1
        date:
            $schema: 'http://json-schema.org/draft-04/schema#'
            type: object
            properties:
                date:
                    type: object
                    properties:
                        forMachine:
                            type: string
                            pattern: '^([12][0-9]{3})-([0-9]{2})-([0-9]{2})$'
                        oneOf:
                            -
                                isExpanded:
                                    enum:
                                        - false
                                forHuman:
                                    type: string
                                    pattern: '^([A-Z][a-z]{2}) ([1-9][0-9]?), ([12][0-9]{3})$'
                            -
                                isExpanded:
                                    enum:
                                        - true
                                    forHuman:
                                        type: object
                                        properties:
                                            dayOfMonth:
                                                type: integer
                                                minimum: 1
                                                maximum: 31
                                            month:
                                                type: integer
                                                minimum: 1
                                                maximum: 12
                                            year:
                                                type: integer
                                        required:
                                            - dayOfMonth
                                            - month
                                            - year
                    required:
                        - forHuman
                        - forMachine
    required:
        - type
        - date
