name: CI Pipeline

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: ["7.1", "7.2", "7.3", "7.4"]
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: make PHP_VERSION=${{ matrix.php_version }} test-ci

  tests-future-versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.0", "8.1", "8.2", "8.3"]
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: make PHP_VERSION=${{ matrix.php_version }} test-ci
        continue-on-error: true
  
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: ["7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]
    steps:
      - uses: actions/checkout@v4
      - name: Run linting
        run: make PHP_VERSION=${{ matrix.php_version }} lint-ci

